In [5]:
import numpy as np


# NumPy basics

In [6]:
b = np.array([[2.0, 3.0, 5.0],[3.0, 6.0, 4.0]])
print(b)

[[2. 3. 5.]
 [3. 6. 4.]]


In [7]:
a = np.array([2,3,4])
print(a)

[2 3 4]


In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [10]:
b.shape

(2, 3)

In [11]:
a.dtype

dtype('int64')

In [12]:
a.itemsize

8

In [13]:
a.size

3

In [14]:
a.itemsize * a.size

24

In [15]:
a.nbytes

24

In [16]:
b.itemsize

8

# Accessing/ Changing specific elements

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
a.shape

(2, 7)

In [19]:
a[1,5]

np.int64(13)

In [20]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
a[:,0]

array([1, 8])

In [23]:
a[0, 1:6:2]

array([2, 4, 6])

In [29]:
a[1,6] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 20]]


In [30]:
a[:, 1] = 5
print(a)

[[ 1  5  3  4  5  6  7]
 [ 8  5 10 11 12 13 20]]


# 3D array

In [35]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print (b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
b[1,0]= [7,8]
print (b)

[[[1 2]
  [3 4]]

 [[7 8]
  [7 8]]]


In [54]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [58]:
np.full((2,3,2), 99)

array([[[99, 99],
        [99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99],
        [99, 99]]])

In [59]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [63]:
np.random.rand(2,2,2)

array([[[0.74062716, 0.07828094],
        [0.35600611, 0.1215862 ]],

       [[0.42127805, 0.32797094],
        [0.26267537, 0.09075484]]])

In [81]:
np.random.randint(-40,50, size=(2,3))

array([[ 38,   8, -26],
       [-27,  -1,  36]])

In [103]:
c = np.ones((5,5))
d = np.zeros((3,3))
d[1,1]=9
c[1:-1,1:-1]=d
print(d)
print(c)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [106]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])