In [5]:
import torch
import numpy as np

In [7]:
list = [[21,2,3,4,5],[6,7,8,9,10]]
list

[[21, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [25]:
np1 = np.random.rand(3,4)
np1

array([[0.25591667, 0.78503743, 0.67560037, 0.75673631],
       [0.53750953, 0.83025234, 0.90117471, 0.51489741],
       [0.19843074, 0.90316422, 0.90692309, 0.83807868]])

In [30]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[-0.7020,  0.4970,  0.5655, -1.1069],
        [-0.1902,  0.0875, -0.5575,  1.8677],
        [ 1.4030, -0.1295,  0.9905, -0.0949]])

In [31]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [32]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2559, 0.7850, 0.6756, 0.7567],
        [0.5375, 0.8303, 0.9012, 0.5149],
        [0.1984, 0.9032, 0.9069, 0.8381]], dtype=torch.float64)

In [33]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape and view

In [34]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [37]:
# Reshape if we dont know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [39]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [41]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
my_torch5[5]

tensor(5)

In [45]:
# Grab a slice
my_torch6 = my_torch5.reshape(5,2)
my_torch6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [46]:
my_torch6[:,1]

tensor([1, 3, 5, 7, 9])

In [47]:
#Return column
my_torch6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])